- name: Add NOPASSWD rule for yay and pacman
  ansible.builtin.copy:
    content: "consular ALL=(ALL) NOPASSWD: /usr/bin/yay, /usr/bin/pacman"
    dest: /etc/sudoers.d/10-ansible-yay
    owner: root
    group: root
    mode: '0440'
  become: true
- name: List common packages
  set_fact:
    common_pkgs:
      - bat
      - btop
      - curl
      - docker
      - eza
      - fish
      - fortune
      - fzf
      - ncdu
      - neovim
      - ripgrep
      - starship
      - yazi
      - zellij
      - zoxide
- name: List casks
  set_fact:
    casks:
      - ghostty
      - tigervnc-viewer
      - zen
- name: List linux GUI apps
  set_fact:
    pkgs:
      - ghostty
      - zen-browser-bin
- name: Install common packages with Homebrew on macOS
  become: false
  community.general.homebrew:
    name: "{{ pkg }}" # Install one package per iteration
    state: present
    update_homebrew: false # Only update brew once, not for each package
  loop: "{{ common_pkgs }}" # Loop over your list of packages
  loop_control:
    loop_var: pkg
  when: ansible_os_family == "Darwin"
- name: Install casks with Homebrew on macOS
  become: false
  community.general.homebrew_cask:
    name: "{{ pkg }}" # Install one package per iteration
    state: present
  loop: "{{ casks }}" # Loop over your list of packages
  loop_control:
    loop_var: pkg
  when: ansible_os_family == "Darwin"
- name: Install common packages with Yay on Arch
  ansible.builtin.command: yay -S --needed --noconfirm {{ pkg }}
  loop: "{{ common_pkgs }}" # Loop over your list of packages
  loop_control:
    loop_var: pkg
  register: yay_install_result
  changed_when: "'installed' in yay_install_result.stdout or 'cloning' in yay_install_result.stdout"
  when: ansible_os_family == "Archlinux"
- name: Install packages with Yay on Arch
  ansible.builtin.command: yay -S --needed --noconfirm {{ pkg }}
  loop: "{{ pkgs }}" # Loop over your list of packages
  loop_control:
    loop_var: pkg
  register: yay_install_result
  changed_when: "'installed' in yay_install_result.stdout or 'cloning' in yay_install_result.stdout"
  when: ansible_os_family == "Archlinux"
