services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    ports:
      - "80:80"
      #- "443:443"
      - "31002:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONFIG_DIR}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      #- "${CONFIG_DIR}/traefik/acme.json:/etc/traefik/acme.json"
    networks:
      - proxy
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    volumes:
      - "${CONFIG_DIR}/adguard/work:/opt/adguardhome/work"
      - "${CONFIG_DIR}/adguard/conf:/opt/adguardhome/conf"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "31001:3000"
      #- "67:67/udp" # Optional: DHCP
      #- "853:853/tcp" # DNS-over-TLS
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`dns.consular.home`)"
      - "traefik.http.routers.adguard.entrypoints=web"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
networks:
  proxy:
    name: "proxy"
