- name: Install gaming dependencies on Arch Linux
  become: true
  block:
    #    - name: List dependencies
    #      set_fact:
    #        pkgs: #- protontricks
    #          - sunshine-bin
    #          - protonup-qt-bin
    #          - proton-ge
    #          - gamescope
    #          - gamemode
    #          - lib32-gamemode
    #          - goverlay
    #          - mangohud
    #          - lutris
    #          - umu-launcher
    #          - power-profiles-daemon
    #          #- wine-staging
    #          - wine-gecko
    #          - openrgb
    #    - name: Install packages
    #      ansible.builtin.command: yay -S --needed --noconfirm {{ pkg }}
    #      loop: "{{ pkgs }}" # Loop over your list of packages
    #      loop_control:
    #        loop_var: pkg
    #      register: yay_install_result
    #      changed_when: "'installed' in yay_install_result.stdout or 'cloning' in yay_install_result.stdout"
    - name: Set cap_sys_admin+p capability on the sunshine executable
      ansible.builtin.command:
        cmd: "setcap cap_sys_admin+p $(readlink -f $(which sunshine))"
    - name: Start the Sunshine user service
      become: no
      ansible.builtin.systemd_service:
        name: sunshine
        state: started
        scope: user
  when: ansible_os_family == "Archlinux"
