on:
  push:
    branches:
      - main:
    paths:
      - 'docker/**'
jobs:
  deploy-docker-stack:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
      - name: Pull and deploy new Docker stack
        run: |
          cd docker
          docker compose pull
          docker compose up -d --remove-orphans
