name: Docker CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
jobs:
  deploy-docker-stack:
    runs-on: docker
    container:
      image: docker/compose:latest
      options: --privileged # Required to access the Docker daemon on the host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull and deploy new Docker stack
        run: |
          cd docker
          docker compose pull
          docker compose up -d --remove-orphans
