name: Docker CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
jobs:
  deploy-docker-stack:
    runs-on: self-hosted # The host that is running your runner container
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull and deploy new Docker stack
        run: |
          cd docker
          docker compose pull
          docker compose up -d --remove-orphans
