version: "3.8"

services:
  gluetun:
    image: docker.io/qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 31104:9117 # expose Jackett through Gluetun
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+OwDWPkQRyKwSubiAxhyETCnj8xEFQMCYHdtwye3UVk=
      - TZ=Asia/Kolkata
      - SERVER_COUNTRIES=Netherlands
    pod: media-vpn

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${MEDIA_DIR}/downloads/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true
    pod: media-vpn

