networks:
  proxy:
    external: true

services:
  jellyseerr:
    restart: unless-stopped
    networks:
      - proxy
    image: docker.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - ${JELLYSEERR_PORT}:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    labels:
      homepage.group: Arr
      homepage.name: Jellyseerr
      homepage.icon: jellyseerr.png
      homepage.href: "http://${IP_ADDR}:${JELLYSEERR_PORT}"
      homepage.description: "Media Request Manager"
  radarr:
    restart: unless-stopped
    networks:
      - proxy
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      homepage.group: Arr
      homepage.name: Radarr
      homepage.icon: radarr.png
      homepage.href: "http://${IP_ADDR}:${RADARR_PORT}"
      homepage.description: "Movie Collection Manager"
  sonarr:
    restart: unless-stopped
    networks:
      - proxy
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      homepage.group: Arr
      homepage.name: Sonarr
      homepage.icon: sonarr.png
      homepage.href: "http://${IP_ADDR}:${SONARR_PORT}"
      homepage.description: "TV Series Manager"
  bazarr:
    restart: unless-stopped
    networks:
      - proxy
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/tv-shows:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      homepage.group: Arr
      homepage.name: Bazarr
      homepage.icon: bazarr.png
      homepage.href: "http://${IP_ADDR}:${BAZARR_PORT}"
      homepage.description: "Subtitle Manager"
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${MEDIA_DIR}/downloads/torrents:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    network_mode: service:gluetun
    labels:
      homepage.group: Arr
      homepage.name: Jackett
      homepage.icon: jackett.png
      homepage.href: "http://${IP_ADDR}:${GLUETUN_JACKETT_PORT}"
      homepage.description: "Indexer Proxy"
  qbittorrent:
    restart: unless-stopped
    networks:
      - proxy
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - ${TORRENT_PORT}:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${MEDIA_DIR}/downloads/torrents:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    labels:
      homepage.group: Arr
      homepage.name: qBittorrent
      homepage.icon: qbittorrent.png
      homepage.href: "http://${IP_ADDR}:${TORRENT_PORT}"
      homepage.description: "Torrent Client"
    #  tdarr:
    #    container_name: tdarr
    #    image: ghcr.io/haveagitgat/tdarr:latest
    #    restart: unless-stopped
    #    network_mode: bridge
    #    ports:
    #      - 31110:8265 # webUI port
    #      - 31160:8266 # server port
    #    environment:
    #      - TZ=Europe/London
    #      #- PUID=${PUID}
    #      #- PGID=${PGID}
    #      - UMASK_SET=002
    #      - serverIP=0.0.0.0
    #      - serverPort=8266
    #      - webUIPort=8265
    #      - internalNode=true
    #      - inContainer=true
    #      - ffmpegVersion=7
    #      - nodeName=MyInternalNode
    #      - auth=false
    #      - openBrowser=true
    #      - maxLogSizeMB=10
    #      - cronPluginUpdate=
    #      - NVIDIA_DRIVER_CAPABILITIES=all
    #      - NVIDIA_VISIBLE_DEVICES=all
    #    volumes:
    #      - ${CONFIG_DIR}/tdarr/server:/app/server
    #      - ${CONFIG_DIR}/tdarr/configs:/app/configs
    #      - ${CONFIG_DIR}/tdarr/logs:/app/logs
    #      - ${MEDIA_DIR}:/media
    #      - ${CONFIG_DIR}/tdarr/transcode_cache:/temp
    #    devices:
    #      - /dev/dri:/dev/dri
