services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/portainer:/data
    networks:
      - proxy
    ports:
      - ${PORTAINER_PORT}:9000
    labels:
      homepage.group: Meta
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: "http://${IP_ADDR}:${PORTAINER_PORT}"
      homepage.description: "Container Management"
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.portainer.rule=Host(`portainer.home.arpa`)"
  #      - "traefik.http.routers.portainer.entrypoints=web"
  #      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    ports:
      - 31000:3000
    volumes:
      - ${CONFIG_DIR}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*" #gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.6.0
    networks:
      - proxy
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
  postgres:
    container_name: postgres_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'Hello@1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - proxy
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
  guacamole:
    container_name: guacamole
    group_add:
      - "1000"
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: 'Hello@1234'
      POSTGRESQL_USERNAME: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole:1.6.0
    networks:
      - proxy
    volumes:
      - ./record:/record:rw
    ports:
      - 31004:8080/tcp
    restart: always
networks:
  proxy:
    name: proxy
    driver: bridge
