services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/portainer:/data
    networks:
      - proxy
    ports:
      - ${PORTAINER_PORT}:9000
    labels:
      homepage.group: Meta
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: "http://${IP_ADDR}:${PORTAINER_PORT}"
      homepage.description: "Container Management"
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.portainer.rule=Host(`portainer.home.arpa`)"
  #      - "traefik.http.routers.portainer.entrypoints=web"
  #      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    ports:
      - 31000:3000
    volumes:
      - ${CONFIG_DIR}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*" #gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "31054:4822"
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "31004:8080"
    links:
      - guacd
    depends_on:
      - guacd
networks:
  proxy:
    name: proxy
    driver: bridge
