networks:
  proxy:
    driver: bridge

services:
  git:
    restart: unless-stopped
    networks:
      - proxy
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ${CONFIG_DIR}/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${GIT_PORT}:3000'
      - '${GIT_SSH_PORT}:22'
    labels:
      homepage.group: Meta
      homepage.name: Forgejo
      homepage.icon: forgejo.png
      homepage.href: "http://${IP_ADDR}:${GIT_PORT}"
      homepage.description: "Self hosted Git"
  portainer:
    restart: unless-stopped
    networks:
      - proxy
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/portainer:/data
    ports:
      - ${PORTAINER_PORT}:9000
    labels:
      homepage.group: Meta
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: "http://${IP_ADDR}:${PORTAINER_PORT}"
      homepage.description: "Container Management"
      #      - "traefik.enable=true"
      #      - "traefik.http.routers.portainer.rule=Host(`portainer.home.arpa`)"
      #      - "traefik.http.routers.portainer.entrypoints=web"
      #      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
