# docker-compose.yml
# This file brings all your service definitions together.
include:
  - apps/feishin.yml
  - apps/immich.yml
  - apps/caddy.yml
  - apps/prowlarr.yml
  #- ai.yml
networks:
  proxy:
    external: true
