services:
  jellyfin:
    extends:
      file: common.yml
      service: common
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/tv-shows:/data/tvshows
      - ${MEDIA_DIR}/movies:/data/movies
    ports:
      - ${JELLYFIN_PORT}:8096
    #      - 8920:8920 #optional
    #      - 7359:7359/udp #optional
    #      - 1900:1900/udp #optional
    labels:
      homepage.group: Media
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: "http://${IP_ADDR}:${JELLYFIN_PORT}"
      homepage.description: "Media Server"
  navidrome:
    extends:
      file: common.yml
      service: common
    container_name: navidrome
    image: deluan/navidrome:latest
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - ${CONFIG_DIR}/navidrome:/data
      - ${MEDIA_DIR}/music:/music:ro
    ports:
      - "${MUSIC_PORT}:4533"
    user: ${PUID}:${PGID}
    labels:
      homepage.group: Media
      homepage.name: Navidrome
      homepage.icon: navidrome.png
      homepage.href: "http://${IP_ADDR}:${MUSIC_PORT}"
      homepage.description: "Music Server"
  audiobookshelf:
    extends:
      file: common.yml
      service: common
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "${BOOKS_PORT}:80"
    volumes:
      - ${MEDIA_DIR}/audiobooks:/audiobooks:ro
      - ${MEDIA_DIR}/podcasts:/podcasts:ro
      - ${CONFIG_DIR}/audiobookshelf:/config
      - ${CONFIG_DIR}/audiobookshelf/metadata:/metadata
    environment:
      - TZ=${TZ}
    user: ${PUID}:${PGID}
    labels:
      homepage.group: Media
      homepage.name: Audiobookshelf
      homepage.icon: audiobookshelf.png
      homepage.href: "http://${IP_ADDR}:${BOOKS_PORT}"
      homepage.description: "Books & Podcasts Server"
