services:
  homepage:
    extends:
      file: common.yml
      service: common
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_DIR}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*" #gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
  guacamole:
    extends:
      file: common.yml
      service: common
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - ${CONFIG_DIR}/guacamole:/config
    ports:
      - ${GUACAMOLE_PORT}:8080
    labels:
      homepage.group: Meta
      homepage.name: Guacamole
      homepage.icon: guacamole.png
      homepage.href: "http://${IP_ADDR}:${GUACAMOLE_PORT}"
      homepage.description: "Access to server UI"
