#- name: "Apply base configuration"
#  hosts: homelab
#  gather_facts: yes
#  become: no
#  #  environment:
#  #    HOMEBREW_CASK_OPTS: "--appdir=/Users/rishi.sharma4/Applications"
#  #    HOMEBREW_NO_AUTO_UPDATE: 1
#  roles:
#    - base
#- name: "Setup Homelab"
#  hosts: homelab
#  gather_facts: yes
#  become: no
#  roles:
#    - self-host
- name: "Setup Gaming Rig"
  hosts: gaming
  gather_facts: yes
  become: no
  roles:
    - gaming
