services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/consular/config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
