- name: Set base variables
  ansible.builtin.set_fact:
    git_repo_url: "https://github.com/ConsularParadi/homelab.git"
    mount: "/mnt/nas"
    clone_destination: "{{ ansible_user_dir }}/homelab"
- name: Set dependent variables
  ansible.builtin.set_fact:
    parent_compose_dir: "{{ clone_destination }}/docker"
    config_dir: "{{ mount }}/config/config"
    media_dir: "{{ mount }}/media/media"
- name: Setup dependencies
  block:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
    - name: Ensure Docker and Docker Compose Plugin are installed
      ansible.builtin.package:
        name:
          - docker
          - docker-compose
        state: present
    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Ensure user is in the docker group for permissions
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
- name: Run docker containers
  block:
    - name: Clone homelab repo
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ clone_destination }}"
      become: false
    - name: Find all compose files
      ansible.builtin.find:
        paths: "{{ parent_compose_dir }}"
        patterns: "*.yml"
      register: compose_files_result
    - name: Deploy the Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ parent_compose_dir }}"
        files: "{{ compose_files_result.files | map(attribute='path') }}"
        state: "present"
      environment:
        CONFIG_DIR: "{{ config_dir }}"
        MEDIA_DIR: "{{ media_dir }}"
      become: true
