cloudflared:
  image: cloudflare/cloudflared:latest
  container_name: cloudflared
  restart: unless-stopped
  network_mode: host
  volumes:
    - "${CONFIG_DIR}/cloudflared:/etc/cloudflared"
  command: tunnel --config /etc/cloudflared/config.yml run homelab
duckdns:
  image: lscr.io/linuxserver/duckdns:latest
  container_name: duckdns
  network_mode: host
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - SUBDOMAINS=tildah
    - TOKEN=2e121305-b828-4f19-8676-a72609034405
    - IPV4_ADDRESS=https://ipv4.icanhazip.com
    - UPDATE_IP=ipv4 #optional
    - LOG_FILE=true #optional
  volumes:
    - "${CONFIG_DIR}/duckdns:/config"
  restart: unless-stopped
